
package com.BFS.action;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "hygyLCEnrolWebService", targetNamespace = "http://server.webservice.hygy.erp.hibernate.byttersoft.com", wsdlLocation = "http://10.0.3.24:8099/erp/services/hygyLCEnrolWebService?wsdl")
public class HygyLCEnrolWebService
    extends Service
{

    private final static URL HYGYLCENROLWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException HYGYLCENROLWEBSERVICE_EXCEPTION;
    private final static QName HYGYLCENROLWEBSERVICE_QNAME = new QName("http://server.webservice.hygy.erp.hibernate.byttersoft.com", "hygyLCEnrolWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.0.3.24:8099/erp/services/hygyLCEnrolWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HYGYLCENROLWEBSERVICE_WSDL_LOCATION = url;
        HYGYLCENROLWEBSERVICE_EXCEPTION = e;
    }

    public HygyLCEnrolWebService() {
        super(__getWsdlLocation(), HYGYLCENROLWEBSERVICE_QNAME);
    }

    public HygyLCEnrolWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HYGYLCENROLWEBSERVICE_QNAME, features);
    }

    public HygyLCEnrolWebService(URL wsdlLocation) {
        super(wsdlLocation, HYGYLCENROLWEBSERVICE_QNAME);
    }

    public HygyLCEnrolWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HYGYLCENROLWEBSERVICE_QNAME, features);
    }

    public HygyLCEnrolWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HygyLCEnrolWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HygyLCEnrolWebServicePortType
     */
    @WebEndpoint(name = "hygyLCEnrolWebServiceHttpSoap11Endpoint")
    public HygyLCEnrolWebServicePortType getHygyLCEnrolWebServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://server.webservice.hygy.erp.hibernate.byttersoft.com", "hygyLCEnrolWebServiceHttpSoap11Endpoint"), HygyLCEnrolWebServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HygyLCEnrolWebServicePortType
     */
    @WebEndpoint(name = "hygyLCEnrolWebServiceHttpSoap11Endpoint")
    public HygyLCEnrolWebServicePortType getHygyLCEnrolWebServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.webservice.hygy.erp.hibernate.byttersoft.com", "hygyLCEnrolWebServiceHttpSoap11Endpoint"), HygyLCEnrolWebServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HYGYLCENROLWEBSERVICE_EXCEPTION!= null) {
            throw HYGYLCENROLWEBSERVICE_EXCEPTION;
        }
        return HYGYLCENROLWEBSERVICE_WSDL_LOCATION;
    }

}
