
package com.BFS.action;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "hygyPaymentWebService", targetNamespace = "http://server.webservice.hygy.erp.hibernate.byttersoft.com", wsdlLocation = "http://10.0.3.24:8099/erp/services/hygyPaymentWebService?wsdl")
public class HygyPaymentWebService
    extends Service
{

    private final static URL HYGYPAYMENTWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException HYGYPAYMENTWEBSERVICE_EXCEPTION;
    private final static QName HYGYPAYMENTWEBSERVICE_QNAME = new QName("http://server.webservice.hygy.erp.hibernate.byttersoft.com", "hygyPaymentWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.0.3.24:8099/erp/services/hygyPaymentWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HYGYPAYMENTWEBSERVICE_WSDL_LOCATION = url;
        HYGYPAYMENTWEBSERVICE_EXCEPTION = e;
    }

    public HygyPaymentWebService() {
        super(__getWsdlLocation(), HYGYPAYMENTWEBSERVICE_QNAME);
    }

    public HygyPaymentWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HYGYPAYMENTWEBSERVICE_QNAME, features);
    }

    public HygyPaymentWebService(URL wsdlLocation) {
        super(wsdlLocation, HYGYPAYMENTWEBSERVICE_QNAME);
    }

    public HygyPaymentWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HYGYPAYMENTWEBSERVICE_QNAME, features);
    }

    public HygyPaymentWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HygyPaymentWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HygyPaymentWebServicePortType
     */
    @WebEndpoint(name = "hygyPaymentWebServiceHttpSoap11Endpoint")
    public HygyPaymentWebServicePortType getHygyPaymentWebServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://server.webservice.hygy.erp.hibernate.byttersoft.com", "hygyPaymentWebServiceHttpSoap11Endpoint"), HygyPaymentWebServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HygyPaymentWebServicePortType
     */
    @WebEndpoint(name = "hygyPaymentWebServiceHttpSoap11Endpoint")
    public HygyPaymentWebServicePortType getHygyPaymentWebServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.webservice.hygy.erp.hibernate.byttersoft.com", "hygyPaymentWebServiceHttpSoap11Endpoint"), HygyPaymentWebServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HYGYPAYMENTWEBSERVICE_EXCEPTION!= null) {
            throw HYGYPAYMENTWEBSERVICE_EXCEPTION;
        }
        return HYGYPAYMENTWEBSERVICE_WSDL_LOCATION;
    }

}
